local M = {}

-- Colorscheme based on Nvimgelion
function M.colorscheme()
  vim.cmd.hi 'clear'

  if vim.fn.exists 'syntax_on' then
    vim.cmd.syntax 'reset'
  end

  vim.g.colors_name = 'vangelion'

  -- Main Colors
  vim.cmd.hi 'Normal guifg=#d5c6e0 guibg=#16161D'
  vim.cmd.hi 'NormalFloat ctermbg=NONE guibg=NONE'
  vim.cmd.hi 'Identifier guifg=#d5c6e0 " hi Identifier guifg=#e2e4f6'
  vim.cmd.hi 'TermCursor cterm=reverse gui=reverse'
  vim.cmd.hi 'Cursor guifg=bg guibg=fg'
  vim.cmd.hi 'lCursor guifg=bg guibg=fg'
  vim.cmd.hi 'CursorLine guibg=#373e40'
  vim.cmd.hi 'CursorColumn guibg=#030707'
  vim.cmd.hi 'CursorLineLir guibg=#984695'
  vim.cmd.hi 'CursorLineNr guifg=#75797a'
  vim.cmd.hi 'LineNr guifg=#686858'
  vim.cmd.hi 'Directory guifg=#fc735d'
  vim.cmd.hi 'EndOfBuffer guifg=#403d39'
  vim.cmd.hi 'IncSearch guibg=#984695'
  vim.cmd.hi 'Search guibg=#984695'
  vim.cmd.hi 'MatchParen guibg=NONE guifg=#9ef01a'
  vim.cmd.hi 'MoreMsg guifg=#7cb375'
  vim.cmd.hi 'ModeMsg cterm=bold gui=bold'
  vim.cmd.hi 'Question guifg=#7cb375'
  vim.cmd.hi 'StatusLine guifg=#75797a'
  vim.cmd.hi 'StatusLineNC guifg=#75797a'
  vim.cmd.hi 'SignColumn guibg=NONE'
  vim.cmd.hi 'VertSplit guifg=#984695 guibg=bg'
  vim.cmd.hi 'Title guifg=#7cb375'
  vim.cmd.hi 'Visual guibg=#703871'
  vim.cmd.hi 'WarningMsg guifg=#fc735d'
  vim.cmd.hi 'WildMenu ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow'
  vim.cmd.hi 'Folded guibg=#030707'
  vim.cmd.hi 'DiffAdd gui=NONE guibg=#182822'
  vim.cmd.hi 'DiffChange gui=NONE guibg=#182822'
  vim.cmd.hi 'DiffDelete gui=NONE guibg=bg'
  vim.cmd.hi 'DiffText gui=NONE guibg=#304936'
  vim.cmd.hi 'Conceal guifg=#7b3f58'
  vim.cmd.hi 'SpellBad cterm=undercurl gui=undercurl guisp=#c51af9'
  vim.cmd.hi 'SpellCap cterm=undercurl gui=undercurl guisp=#fc735d'
  vim.cmd.hi 'SpellRare cterm=undercurl gui=undercurl guisp=#fb3475'
  vim.cmd.hi 'SpellLocal cterm=undercurl gui=undercurl guisp=#d694fa'
  vim.cmd.hi 'Pmenu guibg=#030707'
  vim.cmd.hi 'PmenuSel guifg=#9ef01a  guibg=#403d39'
  vim.cmd.hi 'PmenuSbar guibg=#030707'
  vim.cmd.hi 'TabLine guifg=#75797a'
  vim.cmd.hi 'TabLineSel guifg=#75797a guibg=bg'
  vim.cmd.hi 'TabLineFill guifg=#75797a'
  vim.cmd.hi 'ColorColumn guibg=#030707'
  vim.cmd.hi 'WinBar cterm=bold gui=bold'
  vim.cmd.hi 'FloatShadow guibg=Black blend=80'
  vim.cmd.hi 'FloatShadowThrough guibg=Black blend=100'
  vim.cmd.hi 'RedrawDebugNormal cterm=reverse gui=reverse'
  vim.cmd.hi 'RedrawDebugClear ctermbg=11 guibg=Yellow'
  vim.cmd.hi 'RedrawDebugComposed ctermbg=10 guibg=Green'
  vim.cmd.hi 'RedrawDebugRecompose ctermbg=9 guibg=Red'
  vim.cmd.hi 'Todo guifg=#c51af9'
  vim.cmd.hi 'String guifg=#fcc25d'
  vim.cmd.hi 'Constant guifg=#c51af9'
  vim.cmd.hi 'Function guifg=#fc735d'
  vim.cmd.hi 'Conditional guifg=#b194fa'
  vim.cmd.hi 'Statement guifg=#b194fa'
  vim.cmd.hi 'Repeat guifg=#b194fa'
  vim.cmd.hi 'Operator guifg=#d694fa'
  vim.cmd.hi 'Keyword guifg=#b194fa'
  vim.cmd.hi 'Include guifg=#b194fa'
  vim.cmd.hi 'PreProc guifg=#d694fa'
  vim.cmd.hi 'Type guifg=#7cb375'
  vim.cmd.hi 'Tag guifg=#7cb375'
  vim.cmd.hi 'Special guifg=#fb3475'
  vim.cmd.hi 'Delimiter guifg=#d694fa'
  vim.cmd.hi 'DiagnosticWarn guifg=#fc735d'
  vim.cmd.hi 'DiagnosticInfo guifg=#b194fa'
  vim.cmd.hi 'DiagnosticHint guifg=#75797a'
  vim.cmd.hi 'DiagnosticOk ctermfg=10 guifg=LightGreen'
  vim.cmd.hi 'DiagnosticUnderlineWarn cterm=undercurl gui=undercurl guisp=#fc735d'
  vim.cmd.hi 'DiagnosticUnderlineInfo cterm=undercurl gui=undercurl guisp=#b194fa'
  vim.cmd.hi 'DiagnosticUnderlineHint cterm=undercurl gui=undercurl'
  vim.cmd.hi 'DiagnosticUnderlineOk cterm=underline gui=underline guisp=LightGreen'
  vim.cmd.hi 'Comment cterm=italic gui=italic guifg=#686858'
  vim.cmd.hi 'Underlined cterm=underline ctermfg=81 gui=underline guifg=#80a0ff'
  vim.cmd.hi 'Ignore ctermfg=0 guifg=bg'
  vim.cmd.hi 'CmpItemAbbrDeprecated cterm=strikethrough gui=strikethrough guifg=#75797a'
  vim.cmd.hi 'CmpItemAbbrMatch guifg=#fc735d'
  vim.cmd.hi 'CmpItemAbbrMatchFuzzy guifg=#fc735d'
  vim.cmd.hi 'CmpItemKindVariable guifg=#b194fa'
  vim.cmd.hi 'CmpItemKindInterface guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindText guifg=#fcc25d'
  vim.cmd.hi 'CmpItemKindFunction guifg=#fc735d'
  vim.cmd.hi 'CmpItemKindMethod guifg=#fc735d'
  vim.cmd.hi 'CmpItemKindKeyword guifg=#b194fa'
  vim.cmd.hi 'CmpItemKindProperty guifg=#fcc25d'
  vim.cmd.hi 'CmpItemKindUnit guifg=#7cb375'
  vim.cmd.hi 'CmpItemAbbr guifg=#eaf3f5'
  vim.cmd.hi 'CmpItemAbbrDefault guifg=#eaf3f5'
  vim.cmd.hi 'CmpItemKindDefault guifg=#75797a'
  vim.cmd.hi 'CmpItemKindFile guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindOperator guifg=#c51af9'
  vim.cmd.hi 'CmpItemKindTypeParameter guifg=#fcc25d'
  vim.cmd.hi 'CmpItemKindEnum guifg=#c51af9'
  vim.cmd.hi 'CmpItemKindModule guifg=#fcc25d'
  vim.cmd.hi 'CmpItemKindClass guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindConstant guifg=#c51af9'
  vim.cmd.hi 'CmpItemKindConstructor guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindFolder guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindReference guifg=#b194fa'
  vim.cmd.hi 'CmpItemKindField guifg=#c51af9'
  vim.cmd.hi 'CmpItemKindSnippet guifg=#fcc25d'
  vim.cmd.hi 'CmpItemKindValue guifg=#b194fa'
  vim.cmd.hi 'CmpItemKindEvent guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindStruct guifg=#7cb375'
  vim.cmd.hi 'CmpItemKindEnumMember guifg=#c51af9'
  vim.cmd.hi 'LspReferenceText guibg=#1f1c2a'
  vim.cmd.hi 'LspReferenceRead guibg=#1f1c2a'
  vim.cmd.hi 'LspReferenceWrite guibg=#1f1c2a'
  vim.cmd.hi 'GitSignsChange guifg=#fc735d'
  vim.cmd.hi 'GitSignsDelete guifg=#fb3475'
  vim.cmd.hi 'GitSignsAdd guifg=#7cb375'
  vim.cmd.hi 'GitSignsDeletePreview guifg=#eaf3f5 guibg=#321a26'
  vim.cmd.hi 'GitSignsAddInline guibg=#304936'
  vim.cmd.hi 'TabbyHL_f2e9de_1b2021_NONE guifg=#f2e9de guibg=#1b2021'
  vim.cmd.hi 'TabbyHL_5f506b_1b2021_NONE guifg=#5f506b guibg=#1b2021'
  vim.cmd.hi 'TabbyHL_ffe5d9_5f506b_NONE guifg=#ffe5d9 guibg=#5f506b'
  vim.cmd.hi 'TabbyHL_1b2021_1b2021_NONE guifg=#1b2021 guibg=#1b2021'
  vim.cmd.hi 'TabbyHL_1b2021_5f506b_NONE guifg=#1b2021 guibg=#5f506b'
  vim.cmd.hi 'TabbyHL_f2e9de_5f506b_NONE guifg=#f2e9de guibg=#5f506b'
  vim.cmd.hi 'mkdCodeDelimiter guifg=#75797a'
  vim.cmd.hi 'LspDiagnosticsVirtualTextWarning guifg=#fc735d'
  vim.cmd.hi 'NotifyDEBUGTitle guifg=#75797a'
  vim.cmd.hi 'CmpDocumentation guibg=#030707'
  vim.cmd.hi 'markdownCodeDelimiter guifg=#75797a'
  vim.cmd.hi 'markdownCode guifg=#75797a'
  vim.cmd.hi 'gitcommitSummary guifg=#b194fa'
  vim.cmd.hi 'NotifyDEBUGIcon guifg=#75797a'
  vim.cmd.hi 'NotifyDEBUGBorder guifg=#75797a'
  vim.cmd.hi 'NotifyINFOIcon guifg=#7cb375'
  vim.cmd.hi 'NotifyINFOTitle guifg=#7cb375'
  vim.cmd.hi 'NotifyINFOBorder guifg=#517751'
  vim.cmd.hi 'NotifyWARNTitle guifg=#fc735d'
  vim.cmd.hi 'NotifyWARNIcon guifg=#fc735d'
  vim.cmd.hi 'NotifyWARNBorder guifg=#a14f42'
  vim.cmd.hi 'NotifyERRORTitle guifg=#fb3475'
  vim.cmd.hi 'NotifyERRORIcon guifg=#fb3475'
  vim.cmd.hi 'NotifyERRORBorder guifg=#a02851'
  vim.cmd.hi 'NvimTreeGitDirty guifg=#7cb375'
  vim.cmd.hi 'NvimTreeRootFolder guifg=#7cb375'
  vim.cmd.hi 'TelescopePromptPrefix guifg=#fc735d'
  vim.cmd.hi 'TelescopeMatching guifg=#fc735d'
  vim.cmd.hi 'mkdCde guifg=#75797a'
  vim.cmd.hi 'mkdListItem guifg=#d694fa'
  vim.cmd.hi 'mkdHeading guifg=#fcc25d'
  vim.cmd.hi 'vimOption guifg=#7cb375'
  vim.cmd.hi 'gitcommitDiscardedType guifg=#fb3475'
  vim.cmd.hi 'gitcommitSelectdType guifg=#7cb375'
  vim.cmd.hi 'gitcommitUnmergedFile guifg=#fcc25d'
  vim.cmd.hi 'gitcommitSelectedFile guifg=#7cb375'
  vim.cmd.hi 'gitcommitUnmerged guifg=#7cb375'
  vim.cmd.hi 'gitcommitOverflow guifg=#fb3475'
  vim.cmd.hi 'Noise guifg=#d694fa'
  vim.cmd.hi 'TelescopePromptTitle guibg=#1f1c2a'
  vim.cmd.hi 'NotifyBackground guibg=bg'
  vim.cmd.hi 'LuasnipInsert guifg=#d694fa'
  vim.cmd.hi 'LuasnipChoice guifg=#c51af9'
  vim.cmd.hi 'LirEmptyDirText guibg=#984695'
  vim.cmd.hi 'LirDir guifg=#fc735d'
  vim.cmd.hi 'NotifyLogTitle guifg=#7cb375'
  vim.cmd.hi 'gitcommitHeader guifg=#d694fa'
  vim.cmd.hi 'gitcommitDiscardedFile guifg=#fb3475'
  vim.cmd.hi 'TelescopePromptNormal guibg=#1f1c2a'
  vim.cmd.hi 'TelescopeNormal guibg=#030707'

  -- Lazy.nvim colors
  vim.cmd.hi 'LazyButton guibg=#5a189a'
  vim.cmd.hi 'LazyButtonActive guibg=#d7263d'
  vim.cmd.hi 'LazyDimmed guifg=#686858'
  vim.cmd.hi 'LazyProp guifg=#686858'
  vim.cmd.hi 'LazyCommit guifg=#aaaaaa'
  vim.cmd.hi 'LazyCommitType guifg=#aaa1c8'

  -- Colors using Treesitter tokens
  vim.cmd.hi '@tag.delimiter guifg=#75797a'
  vim.cmd.hi '@text.literal guifg=#75797a'
  vim.cmd.hi '@text.reference guifg=#fcc25d'
  vim.cmd.hi '@text.uri cterm=underline gui=underline guifg=#b194fa'
  vim.cmd.hi '@text.strong cterm=bold gui=bold'
  vim.cmd.hi '@text.emphasis cterm=italic gui=italic'
  vim.cmd.hi '@constructor.python guifg=#8bd450'
  vim.cmd.hi '@field.python guifg=#b8b8ff'
  vim.cmd.hi '@variable.builtin.python guifg=#8bd450'
  vim.cmd.hi 'link @attribute.python Special'

  -- lukas-reineke/indent-blankline
  vim.cmd.hi 'IndentBlanklineChar gui=nocombine guifg=#444C55'
  vim.cmd.hi 'IndentBlanklineSpaceChar cterm=nocombine ctermfg=NONE gui=nocombine guifg=#4d5154'
  vim.cmd.hi 'IndentBlanklineContextChar gui=nocombine guifg=#FB5E2A'
  vim.cmd.hi 'IndentBlanklineContextStart gui=underline guisp=#FB5E2A'
  vim.cmd.hi 'IblIndent gui=nocombine guifg=#444C55'
  vim.cmd.hi 'IblScope gui=nocombine guifg=#FB5E2A'

  -- NOTE: My custom additions/changes
  vim.cmd.hi 'Comment cterm=italic gui=italic guifg=#b9b9ac' -- Darkish Gray
  vim.cmd.hi 'DiagnosticHint guifg=#f2f2f3' -- Lightish Gray
  vim.cmd.hi 'CursorLineNr guifg=#6685ff' -- Blueish
  vim.cmd.hi 'LineNr guifg=#997a00' -- Mustard Yellow
  vim.cmd.hi 'Identifier guifg=#6666ff' -- Purple-ish Blue
  vim.cmd.hi 'CurSearch guifg=#262626 guibg=#1B9AAA' -- Purple-ish Blue
  vim.cmd.hi 'IncSearch guifg=#262626 guibg=#1B9AAA' -- Purple-ish Blue
  vim.cmd.hi 'Search guifg=#d7d7d7 guibg=#885A89' -- Purple-ish Blue
  vim.cmd.hi 'Visual guifg=#d9d9d9 guibg=#13315C' -- Purple-ish Blue
  vim.cmd.hi 'FloatBorder guifg=#d7d7d7'
  vim.cmd.hi 'LspInlayHint guifg=#75797a'
  vim.cmd.hi 'MsgSeparator guifg=#826e17 guibg=#262626 gui=bold' -- DARK Gray
end

return M
